# Generated by Django 3.2 on 2021-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name_customer',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
